-- ============================================================
-- VIDAGE COMPLET DE LA BASE (TRUNCATE)
-- À exécuter dans l'éditeur SQL de Supabase avant un nouvel import
-- ============================================================

TRUNCATE TABLE 
    larcauth_student_has_weekevents,
    larcauth_student_has_termevents,
    larcauth_student_has_events,
    larcauth_student_has_dayevents,
    larcauth_agenda,
    larcauth_termsubject_has_homework,
    larcauth_unit,
    larcauth_evaluation,
    larcauth_learnerpp_has_termsubjectpp,
    larcauth_learnerpei_has_termsubjectpei,
    larcauth_learnerdp_has_termsubjectdp,
    larcauth_learnerprim_has_unit_period,
    larcauth_learnermat_has_unit_period,
    larcauth_learnermat_has_subjectevals_unit,
    larcauth_learnermat_has_devpers_unit,
    larcauth_learner_has_termothersubject,
    larcauth_learner_has_termsubject,
    larcauth_learner_has_term,
    larcauth_learner_has_subjectgroup,
    larcauth_levelsubject,
    larcauth_criteria_of_levelsubject,
    larcauth_criteria_of_subjectsgroup,
    larcauth_mat_subjectevals_unit,
    larcauth_mat_subjectskills_unit,
    larcauth_mat_subjectskills,
    larcauth_mat_devpers_unit,
    larcauth_mat_devpers_gene,
    larcauth_mat_unit,
    larcauth_edt_classe,
    larcauth_classroom_has_timeperiod,
    larcauth_classroom_termothersubject,
    larcauth_classroom_termsubject,
    larcauth_classroom,
    larcauth_teachadm,
    larcauth_student,
    larcauth_aecuser,
    larcauth_natureparentutor,
    larcauth_type_event,
    larcauth_timeperiod,
    larcauth_lieu,
    larcauth_globalcontext,
    larcauth_concept,
    larcauth_subjectgroup,
    larcauth_level,
    larcauth_campus,
    larcauth_unit_period,
    larcauth_term,
    larcauth_academicyear,
    larcauth_program,
    larcauth_gender,
    larcauth_district,
    larcauth_language
CASCADE;
